### ISSUE TITLE
how to install gpu support to train by gpu?

### ISSUE THREAD

**Issue by qhbsss** [yetinam/TEAM#2]

**Comment by yetinam** [comment]
To install GPU support, you'll need to install tensorflow with GPU support. Please mind that TEAM uses tensorflow 1.14. Probably the easiest option will be through conda.

**Comment by qhbsss** [comment]
After gpu support is installed, it's seems that train process is still through cpu. Does the codes need to be revised to adjust the gpu support?

**Comment by yetinam** [comment]
As far as I remember, the code should automatically run on GPU if available. You can uncomment the line `print(device_lib.list_local_devices())` at the start of `train.py` to print all available devices and verify the GPU support is properly installed.
